# Generated by Django 5.0.1 on 2024-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_decription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='decription',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=288),
        ),
    ]
