# Generated by Django 5.0.1 on 2024-01-15 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactPlusDjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artivle',
            new_name='Article',
        ),
    ]
